name: Getusers

on:
  push:
  schedule:
    - cron: '0 16 * * *'

jobs:
  Ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout actions
      uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Get user list
      run: |        
        python -m pip install requests
        python get-users.py
    - name: Commit
      run: |
        git config --global user.email gwynding88@outlook.com
        git config --global user.name Rusmere
        git add .
        git commit -m "update" -a

      # Runs a single command using the runners shell
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

